template = ""
rev_id = 332
template_sha = "517a754a9d968919fdaa1ed6e00d20145fac402c"

[replacements]
__GLOTTOLOG_ID__ = "anam1249"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-aan"
__UND2C__ = "aan"
__UNDEFINED__ = "Anambé"
__UND__ = "aan"
