template = ""
rev_id = 344
template_sha = "5adf8b2fc54441e99d8cd7357dc342d2e77ed5ac"

[replacements]
__GLOTTOLOG_ID__ = "anam1249"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-aan"
__UND2C__ = "aan"
__UNDEFINED__ = "Anambé"
__UND__ = "aan"
