template = ""
rev_id = 303
template_sha = "2ae3f964876faa6636309f7d609478512097ebd0"

[replacements]
__GLOTTOLOG_ID__ = "anam1249"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-aan"
__UND2C__ = "aan"
__UNDEFINED__ = "Anambé"
__UND__ = "aan"
